### ISSUE TITLE
Skip proxying and just send a response

### ISSUE THREAD

**Issue by VinceG3** [igrigorik/em-proxy#46]
I'm trying to implement a basic reverse proxy, and mostly got it working, it uses a regular expression to pull the Host field from the request and picks a local server to proxy from based on that. I would like it if it doesn't find a server based on that regular expression, to simply reply with a 404 or "it works" or something. But it won't let me not configure a server, I get:

    home/vince/.gem/ruby/2.1.3/gems/em-proxy-0.1.8/lib/em-proxy/connection.rb:31:in `relay_to_servers': undefined method `collect' for nil:NilClass (NoMethodError)

Is there a way to get it to just stop and return a response?

**Comment by igrigorik** [comment]
If you return `nil` or `:async`, it'll skip the relay logic. See: https://github.com/igrigorik/em-proxy/blob/master/lib/em-proxy/connection.rb#L22
