### ISSUE TITLE
Select backend on request data

### ISSUE THREAD

**Issue by pbruna** [igrigorik/em-proxy#47]
I'm starting to understand that maybe this is not possible, but I need to know for sure.
It's possible to select a backend based on the value of a params request or/and Header value?

I know some proxies do this, that's why we have sticky session, but for what I have been trying, em-proxy start to relay data to the backend as soon as it receives it.

Is there anyway to implement this with em-proxy?

**Comment by igrigorik** [comment]
Check out the http_proxy example, it does more or less exactly what you're looking for: https://github.com/igrigorik/em-proxy/blob/master/examples/http_proxy.rb#L18 - waits until headers are processed and then forwards the request. You'd just need to add own logic to pick the appropriate backend.

**Comment by pbruna** [comment]
Thanks.
