### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by georgeu2000** [igrigorik/em-proxy#48]
em-proxy -l 80 -r localhost:3000 -v
    /.../gems/em-proxy-0.1.8/lib/em-proxy/proxy.rb:4: warning: epoll is not supported on this platform`

Ruby 2.2.0

**Comment by igrigorik** [comment]
Hmm, this is not a em-proxy issue.. This is eventmachine, see: https://github.com/eventmachine/eventmachine/blob/master/docs/old/EPOLL
