### ISSUE TITLE
Missing LICENSE file in rubygem

### ISSUE THREAD

**Issue by Germano0** [igrigorik/em-proxy#56]
Hi, I am Germano from Fedora community. I am going to package em-proxy and include it into Fedora repositories. We found out that the LICENSE file is missing in rubygem file from https://rubygems.org.

Fedora package review process for em-proxy https://bugzilla.redhat.com/show_bug.cgi?id=1348160

Have a nice day

**Comment by igrigorik** [comment]
Thanks for the nudge :)

Pushed 0.1.9 to rubygems. Let me know if anything else comes up!
