### ISSUE TITLE
Syntax error in examples/http_proxy.rb

### ISSUE THREAD

**Issue by icy** [igrigorik/em-proxy#58]
Please see https://github.com/igrigorik/em-proxy/blob/master/examples/http_proxy.rb#L38 . Ruby can't parse the code.

**Comment by igrigorik** [comment]
Doh. My bad. Thanks for reporting this, fixed in https://github.com/igrigorik/em-proxy/commit/93c8f3f00bc3f542a84341d0a1d64c4a756e9ba4.
