### ISSUE TITLE
2 network

### ISSUE THREAD

**Issue by xor256** [igrigorik/em-proxy#59]
I have 2 network and would like using a one browser to load files, web pages.
Is possible to using 2 different ip as one in this same time?
for example 2 providers  
10.0.0.1 one default routing
and 10.0.0.2 for other default routing

**Comment by igrigorik** [comment]
Not clear on what you're asking.. As in, can you use em-proxy to select which network interface to use for outgoing connections? No.. you have to bind to a particular interface. That said, I think what you're looking for is "network bonding" -- search for that on the internets :-)

**Comment by sp00ck** [comment]
Maybe it is worth creating this program?
Easy way to improve network speed?
think about it
